[project]
name = "ticket-triage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Evangelos Organtzoglou", email = "eorgantzoglou@uth.gr" }
]
requires-python = ">=3.11"
dependencies = [
    "openai>=2.53.0",
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
